### ISSUE TITLE
Build failure due to missing godep

### ISSUE THREAD

**Issue by optimusbrine** [noffle/ipget#15]
It seems that the vendoring of some of IPFS's dependencies with GoDep broke here:
```
package github.com/noffle/ipget/Godeps/_workspace/src/github.com/Sirupsen/logrus: cannot find package "github.com/noffle/ipget/Godeps/_workspace/src/github.com/Sirupsen/logrus" in any of:
 
[...]

        /home/jesse/stuff/src/github.com/noffle/ipget/Godeps/_workspace/src/github.com/Sirupsen/logrus (from $GOPATH)
```
I tracked the reference down to several source files in:
`Godeps/_workspace/src/github.com/ipfs/go-ipfs/vendor/QmXJkcEXB6C9h6Ytb6rrUTFU56Ro62zxgrbxTT3dgjQGA8/go-log/`

**Comment by noffle** [comment]
Thanks for the report, @optimusbrine! I've included the missing dep and pushed -- it should build now. This shouldn't happen again once #2 happens.
